version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/DevergoLabs

permissions:
  - object: /home/ubuntu/DevergoLabs
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: code-deploy-scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: code-deploy-scripts/after_install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: code-deploy-scripts/start_app.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: code-deploy-scripts/validate_service.sh
      timeout: 300
      runas: root
